services:
  hickory-dns:
    build: .
    image: hickory-dns:latest
    ports:
      - "5301:5301/tcp"
      - "443:443"
    volumes:
      - ./config:/config
    restart: unless-stopped
    command: -c /config/routedns-pipeline.toml -z /config/
